# 使用说明：在 package.json 中定义命令；
# 注意事项：先要把改动 push 到主分支，因为发布成功会会自动 pull 线上主分支；
# 安装：npm run 安装
# 本地：npm run 本地
# 发布：npm run 发布

# Mandatory settings

blog_theme: light # Or use dark
name: 少亭
paginate: 25
url: https://gushaoting.com


# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
ga_analytics: UA-45131556-2 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
social:
  email: biaopiao@gmail.com # Add your Email address


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
